Algoritmo "Ex002"
//2) Faça um programa que leia o nome de uma pessoa e
//mostre uma mensagem de boasvindas para ela:
//Ex:
//Qual é o seu nome? João da Silva
//Olá João da Silva, é um prazer te conhecer!

Var
  Nome: Caractere // declaração da variavel nome
Inicio
  Escreva("Digite seu nome: ") //mensagem para continuidade de comando de entrada
  Leia(Nome)// comando de entrada
  Escreva("Olá ",Nome,", é um prazer te conhecer!") //saida de info completa

Fimalgoritmo